TELEMET/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.urls import include
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path('board/', include('board.urls')),
    path('equipamiento/', include('equipamiento.urls')),
    path('ubicaciones/', include('ubicaciones.urls')),
    path('', RedirectView.as_view(url='/board/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += i18n_patterns(path("admin/", admin.site.urls))

board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('error/', views.error, name='error'),
    path('board/', views.board, name='board'),
    path('obtener_localidades/', views.obtener_localidades, name='obtener_localidades'),
    path('localidades/', views.lista_localidades, name='lista_localidades'),
    path('search/', views.search, name='search'),

]

board/models.py
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)





class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'



# class PermisosUsuarios(models.Model):
#     id_permiso_usuario = models.AutoField(primary_key=True)
#     id_user = models.ForeignKey('Users', models.DO_NOTHING, db_column='id_user')
#     id_modulo = models.ForeignKey(Modulos, models.DO_NOTHING, db_column='id_modulo')
#     id_submodulo = models.PositiveIntegerField()
#
#     class Meta:
#         managed = False
#         db_table = 'permisos_usuarios'



# class Users(models.Model):
#     id_user = models.AutoField(primary_key=True)
#     cedula = models.IntegerField()
#     name = models.CharField(max_length=100)
#     email = models.CharField(unique=True, max_length=150)
#     telefono = models.CharField(max_length=9)
#     direccion = models.CharField(max_length=50)
#     pass_field = models.CharField(db_column='pass', max_length=90)  # Field renamed because it was a Python reserved word.
#     tmp_pass = models.CharField(max_length=90, blank=True, null=True)
#     token = models.CharField(max_length=90, blank=True, null=True)
#     is_teleimpresores = models.CharField(max_length=1)
#     reset_pass = models.CharField(max_length=1)
#     id_region = models.ForeignKey(Regiones, models.DO_NOTHING, db_column='id_region', blank=True, null=True)
#
#     class Meta:
#         managed = False
#         db_table = 'users'

board/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import JsonResponse
from ubicaciones.models import Localidades, Coordenadas, Departamentos, Regiones, Sectores
from django.core.paginator import Paginator
from django.db.models import Q

#################################################################################
def board(request):
    localidades = Localidades.objects.all()
    paginator = Paginator(localidades, 5)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(request, 'board/board.html', {'page': page})

#################################################################################
def index(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('board:board')
        else:
            return redirect('board:error')

    return render(request, 'board/index.html')

#################################################################################
def error(request):
    return render(request, 'board/error.html')

#################################################################################
def board(request):
    return render(request, 'board/board.html')


#################################################################################
def obtener_localidades(request):
    localidades = Localidades.objects.all()
    data = []

    for localidad in localidades:
        coordenadas = localidad.coordenadas_set.first()  # Acceso a la relación ForeignKey

        if coordenadas:
            latitud = coordenadas.latitud
            longitud = coordenadas.longitud
        else:
            # Si las coordenadas están vacías, proporciona valores por defecto
            latitud = 0
            longitud = 0

        data.append({
            'latitud': latitud,
            'longitud': longitud,
            'nombre': localidad.localidad,
            'departamento': localidad.id_departamento.departamento,
            'region': localidad.id_departamento.id_region.region,
        })

    return JsonResponse(data, safe=False)

#################################################################################
def lista_localidades(request):
    localidades = Localidades.objects.all()
    paginator = Paginator(localidades, 4)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    data = []

    for localidad in page:
        coordenadas = localidad.coordenadas_set.first()

        if coordenadas:
            latitud = coordenadas.latitud
            longitud = coordenadas.longitud
        else:
            latitud = 0
            longitud = 0

        data.append({
            'latitud': latitud,
            'longitud': longitud,
            'nombre': localidad.localidad,
            'departamento': localidad.id_departamento.departamento,
            'region': localidad.id_departamento.id_region.region,
        })

    return JsonResponse({
        'localidades_data': data,
        'has_previous': page.has_previous(),
        'has_next': page.has_next(),
        'pages': paginator.num_pages,
        'current_page': page.number,
    })

#################################################################################

def search(request):
    query = request.GET.get('q')

    # Búsqueda en el modelo Departamentos
    departamentos = Departamentos.objects.filter(
        Q(departamento__icontains=query) |
        Q(id_region__region__icontains=query)
    )

    # Búsqueda en el modelo Regiones
    regiones = Regiones.objects.filter(
        Q(region__icontains=query) |
        Q(departamentos__departamento__icontains=query)
    )

    # Búsqueda en el modelo Localidades y Sectores (sin cambios)
    localidades = Localidades.objects.filter(Q(localidad__icontains=query))
    sectores = Sectores.objects.filter(sector__icontains=query)

    results_dict = {
        'departamentos': [str(departamento) for departamento in departamentos],#
        'localidades': [str(localidad) for localidad in localidades],
        'regiones': [str(region) for region in regiones], #
        'sectores': [str(sector) for sector in sectores],
    }

    # Imprime los resultados en el terminal
    print("Resultados de búsqueda:")
    print("Departamentos:", results_dict['departamentos'])
    print("Localidades:", results_dict['localidades'])
    print("Regiones:", results_dict['regiones'])
    print("Sectores:", results_dict['sectores'])

    return JsonResponse(results_dict)

board/templates/board/board.html
{% extends 'board/base.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-md-4">
<h3>Localidades</h3>
    <ol class="list-group list-group-numbered" id="localidades-container"></ol>
        <br>
        <nav aria-label="Page navigation">
        <ul class="pagination" id="pagination-container">
            <li class="page-item" id="prevPageBtn">
                <a class="page-link" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            <li class="page-item" id="nextPageBtn">
                <a class="page-link" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
    </div>



    <div class="col-md-8">
        <br>
        <h4>Búsqueda por localidades o sectores</h4>
        <form id="search-form" class="form-inline my-2 my-lg-0" method="GET" action="">
      <input class="form-control mr-sm-2" id="search-input" name="q" type="search" placeholder="Search" aria-label="Buscar por....">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    </form>

        <br>
        <div id="map" style="height: 350px;"></div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="../../../static/js/mapa.js"></script>
<script src="../../../static/js/localidades.js"></script>
<script src="../../../static/js/buscador_board.js"></script>
{% endblock %}

board/templates/board/error.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Sistema de Gestión PPCC{% endblock %}</title>
    {% load static %}

    <link href="../static/css/bootstrap.min.css" rel="stylesheet">
    <meta http-equiv="refresh" content="5;url={% url 'board:index' %}">
</head>
<body>
<br>
<br>
<br>
<div style="text-align: center;">
    <img class="mb-4" src="../static/images/error.png" width="200" height="200" style="margin: auto;">
    <h3 style="text-align: center;">Redirigiendo a la página de inicio en 5 segundos...</h3>
    <br>
    <br>
    <div class="spinner-border text-primary" role="status" style="font-size: 9rem;">
  <span class="visually-hidden">Loading...</span>
</div>
</div>

</body>
</html>

board/templates/board/index.html
<!doctype html>
<html lang="es" data-bs-theme="auto">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Sistema de Gestión PPCC</title>
      <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/sign-in/">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">


      <style>
          .bd-placeholder-img {
              font-size: 1.125rem;
              text-anchor: middle;
              -webkit-user-select: none;
              -moz-user-select: none;
              user-select: none;
          }

          @media (min-width: 768px) {
              .bd-placeholder-img-lg {
                  font-size: 3.5rem;
              }
          }


          .b-example-divider {
                width: 100%;
                height: 3rem;
                background-color: rgba(0, 0, 0, .1);
                border: solid rgba(0, 0, 0, .15);
                border-width: 1px 0;
                box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
          }

          .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
          }

          .bi {
            vertical-align: -.125em;
            fill: currentColor;
          }

          .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
          }

          .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
          }

          .btn-bd-primary {
        --bd-violet-bg: #2c93f9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #2c93f9;
        --bs-btn-hover-border-color: #2c93f9;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #2c93f9;
        --bs-btn-active-border-color: #2c93f9;
      }
          .bd-mode-toggle {
            z-index: 1500;
          }
        </style>

<link href="../../../static/css/sign-in.css" rel="stylesheet">
    <script src="../../../static/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="../../../static/css/bootstrap.min.css">
    <script src="../../../static/js/color-modes.js"></script>
  </head>
  <body class="d-flex align-items-center py-4 bg-body-tertiary">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>


<main class="form-signin w-100 m-auto">

    <form method="post" action="{% url 'board:index' %}">
            {% csrf_token %}
    <img class="mb-4" src="../../../static/images/OSE.svg" alt="" width="280">


    <div class="form-floating">
      <input type="text" class="form-control" id="floatingInput" name="username" placeholder="Nombre de Usuario">
      <label for="floatingInput">Usuario</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Contraseña">
      <label for="floatingPassword">Password</label>
    </div>

    <button class="btn btn-primary w-100 py-2" type="submit">Ingreso</button>

  </form>
</main>

    </body>
</html>